#!/usr/bin/env node
/**
 * Assumption registry generator.
 *
 * The Mumbai One bug was `country: "us"` — a hidden product decision wearing
 * the costume of ordinary code. Nobody could review it, because nobody could
 * SEE it: it looked like a parameter, not a bet about who our customers are.
 *
 * So every embedded product bet now carries an `@assumption` tag, and this
 * script collects them into docs/ASSUMPTIONS.md. The registry is reviewed
 * against docs/PRODUCT_CONTEXT.md in every audit round: an assumption that
 * contradicts the customer brief is a bug, whether or not anything has
 * broken yet.
 *
 *   node scripts/assumptions.mjs          # print
 *   node scripts/assumptions.mjs --write  # regenerate docs/ASSUMPTIONS.md
 *
 * Format in code:
 *   // @assumption <what we are betting> | risk: <what breaks if wrong>
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const SRC = join(ROOT, "src");
const OUT = join(ROOT, "docs", "ASSUMPTIONS.md");

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules" || entry === ".next") continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (/\.(ts|tsx)$/.test(entry) && !/\.test\.tsx?$/.test(entry)) out.push(full);
  }
  return out;
}

const findings = [];
for (const file of walk(SRC)) {
  const lines = readFileSync(file, "utf8").split("\n");
  lines.forEach((line, i) => {
    const match = line.match(/@assumption\s+(.+)$/);
    if (!match) return;
    const [claim, risk] = match[1].split("| risk:").map((s) => s?.trim() ?? "");
    findings.push({
      where: `${relative(ROOT, file)}:${i + 1}`,
      claim: claim.replace(/\*\/\s*$/, "").trim(),
      risk: (risk || "—").replace(/\*\/\s*$/, "").trim(),
    });
  });
}

findings.sort((a, b) => a.where.localeCompare(b.where));

const doc = `# Assumption Registry

<!-- GENERATED by scripts/assumptions.mjs — do not edit by hand.
     Add an @assumption tag in the code instead. -->

Every product bet embedded in the code, made visible so it can be reviewed
against **docs/PRODUCT_CONTEXT.md**.

**How to use this in an audit:** read each row and ask *"is this still true for
the customer we actually have?"* — not *"is this code correct?"*. The
\`country: "us"\` default that hid the Mumbai One bug for months was correct
code and a wrong bet. Only this question finds that class of defect.

${findings.length} assumptions found.

| Where | We are betting that… | If wrong… |
|---|---|---|
${findings.map((f) => `| \`${f.where}\` | ${f.claim} | ${f.risk} |`).join("\n")}

---

Tag a new one in code as:

\`\`\`ts
// @assumption Reviews older than 14 days do not matter | risk: customers with slow review cycles see an empty inbox
\`\`\`
`;

if (process.argv.includes("--write")) {
  writeFileSync(OUT, doc);
  console.log(`Wrote ${relative(ROOT, OUT)} (${findings.length} assumptions)`);
} else {
  console.log(doc);
}
